import { S as e, c as t, i as n, n as r, p as i, r as a, t as o, w as s, x as c } from "./ui-BRNtr3Vo.js";
import { S as l } from "./index-BqZ61Way.js";
var u = s(e(), 1),
  d = c(),
  f = [`AI Available (simulated)`, `Quota Limited`, `Disabled`, `Configuration Pending`];
function p({ audience: e, actions: s, title: c }) {
  let [p, m] = (0, u.useState)(`AI Available (simulated)`),
    [h, g] = (0, u.useState)(``),
    [_, v] = (0, u.useState)(null),
    y = e === `Student` ? 50 : 100,
    b = p === `Quota Limited` ? y : e === `Student` ? 12 : 37,
    x = p === `AI Available (simulated)`;
  return (0, d.jsxs)(`div`, {
    className: `mx-auto max-w-5xl`,
    children: [
      (0, d.jsx)(t, { title: c, subtitle: `${e} Study Assistant prototype · advisory only · no AI provider connected` }),
      (0, d.jsxs)(n, {
        className: `mb-4`,
        children: [
          (0, d.jsx)(`p`, { className: `mb-2 text-sm font-medium`, children: `Preview assistant status:` }),
          (0, d.jsx)(i, { tabs: f, value: p, onChange: m, label: `Assistant status` }),
          (0, d.jsxs)(`p`, {
            className: `text-sm`,
            children: [
              `Usage today (IST): `,
              (0, d.jsxs)(`strong`, { children: [b, ` / `, y] }),
              ` successful user-requested responses · approved pilot limit `,
              y,
              ` per IST day.`,
            ],
          }),
        ],
      }),
      (0, d.jsxs)(`div`, {
        className: `grid gap-4 lg:grid-cols-3`,
        children: [
          (0, d.jsxs)(n, {
            className: `lg:col-span-2`,
            title: `Ask`,
            children: [
              (0, d.jsx)(`div`, {
                className: `mb-3 flex flex-wrap gap-2`,
                children: s.map((e) =>
                  (0, d.jsx)(a, { variant: `outline`, disabled: !x, onClick: () => v({ q: h || e, action: e }), children: e }, e),
                ),
              }),
              (0, d.jsx)(`label`, { htmlFor: `askq`, className: `mb-1 block text-sm font-medium`, children: `Your question` }),
              (0, d.jsx)(`textarea`, {
                id: `askq`,
                rows: 3,
                value: h,
                onChange: (e) => g(e.target.value),
                className: `w-full rounded-lg border border-input bg-card p-3`,
                placeholder: `e.g. Explain logistic regression / లాజిస్టిక్ రిగ్రెషన్ వివరించండి`,
              }),
              (0, d.jsx)(`div`, {
                className: `mt-2`,
                children: (0, d.jsxs)(a, {
                  disabled: !x || !h,
                  onClick: () => v({ q: h, action: `Ask about my course` }),
                  children: [(0, d.jsx)(l, { className: `size-4`, "aria-hidden": !0 }), `Ask (simulated)`],
                }),
              }),
              !x &&
                (0, d.jsxs)(`p`, {
                  role: `alert`,
                  className: `mt-2 text-sm font-medium text-warning`,
                  children: [
                    `⚠ `,
                    p === `Quota Limited`
                      ? `Daily limit of ${y} responses reached. Resets at 00:00 IST.`
                      : p === `Disabled`
                        ? `Assistant disabled by administrator.`
                        : `Assistant Configuration Pending — no approved provider or spend ceiling yet.`,
                  ],
                }),
              _ &&
                x &&
                (0, d.jsxs)(`div`, {
                  className: `mt-4 rounded-lg border bg-muted p-3 text-sm`,
                  children: [
                    (0, d.jsx)(r, { tone: `sim`, children: `Simulated response — not generated by any AI` }),
                    (0, d.jsxs)(`p`, {
                      className: `mt-2`,
                      children: [
                        (0, d.jsxs)(`strong`, { children: [_.action, `:`] }),
                        ` “`,
                        _.q,
                        `”. A grounded answer would appear here, limited to your enrolled course scope.`,
                      ],
                    }),
                    (0, d.jsxs)(`div`, {
                      className: `mt-3 grid gap-2 sm:grid-cols-2`,
                      children: [
                        (0, d.jsxs)(`div`, {
                          children: [
                            (0, d.jsx)(`p`, { className: `text-xs font-semibold`, children: `Sources / Evidence` }),
                            (0, d.jsxs)(`ul`, {
                              className: `list-disc pl-4 text-xs`,
                              children: [
                                (0, d.jsx)(`li`, { children: `Regression notes (PDF), Track 2 CV 2.4` }),
                                (0, d.jsx)(`li`, { children: `Session ses-102 transcript — Held, excluded` }),
                              ],
                            }),
                          ],
                        }),
                        (0, d.jsxs)(`div`, {
                          children: [
                            (0, d.jsx)(`p`, { className: `text-xs font-semibold`, children: `Scope & freshness` }),
                            (0, d.jsx)(`p`, { className: `text-xs`, children: `NIT-CRS-018 · Track 2 · content as of 25 Sep 2026` }),
                          ],
                        }),
                      ],
                    }),
                    (0, d.jsx)(`p`, {
                      className: `mt-2 text-xs text-warning`,
                      children: `⚠ Missing Data / Warnings: engagement data is Stale; one recording held for review.`,
                    }),
                  ],
                }),
            ],
          }),
          (0, d.jsxs)(n, {
            title: `Spend controls`,
            children: [
              (0, d.jsxs)(`ul`, {
                className: `list-disc space-y-1 pl-5 text-sm`,
                children: [
                  (0, d.jsx)(`li`, { children: `Chargeable AI requires a Founder/CEO-approved monthly rupee ceiling.` }),
                  (0, d.jsx)(`li`, { children: `Warning at 80% of the ceiling.` }),
                  (0, d.jsx)(`li`, { children: `Additional chargeable requests stop at the ceiling.` }),
                ],
              }),
              (0, d.jsx)(`div`, {
                className: `mt-2`,
                children: (0, d.jsx)(r, { children: `Configuration Pending — ceiling not yet approved` }),
              }),
              (0, d.jsx)(`div`, {
                className: `mt-3`,
                children: (0, d.jsx)(o, { children: `No AI provider is connected. Answers are advisory and permission-aware.` }),
              }),
            ],
          }),
        ],
      }),
    ],
  });
}
export { p as t };
